version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword123
    # MONGO_INITDB_DATABASE is optional; we'll use init script to create multiple DBs & users
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d   # mount init scripts
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: